# Generated by Django 5.1.4 on 2026-04-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=20)),
                ('full_name', models.TextField()),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('compensation', models.IntegerField(default=0)),
                ('email', models.TextField(blank=True, null=True)),
                ('email_status', models.CharField(blank=True, max_length=30, null=True)),
                ('email_source', models.CharField(blank=True, max_length=30, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=20, unique=True)),
                ('name', models.TextField()),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('revenue', models.BigIntegerField(default=0)),
                ('assets', models.BigIntegerField(default=0)),
                ('ntee_code', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('has_property', models.IntegerField(default=0)),
                ('fiscal_year_end', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('discover', 'Stage 1 — Discover'), ('enrich', 'Stage 2 — Enrich'), ('scrape', 'Stage 3 — Scrape'), ('emails', 'Stage 4 — Emails'), ('export', 'Stage 5 — Export'), ('all', 'Full Pipeline')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True, default='')),
                ('orgs_found', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pipeline_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
